### ISSUE TITLE
Some issues when running drake

### ISSUE THREAD

**Issue by Simon-Fuhaoyuan** [caelan/pddlstream#12]
Hello, I'm trying to run the demo in drake. However, I find that pydrake only supports python3 now, and the document of drake API changes a lot from your codes. Can you please show your environment settings of the demo of drake? The settings should include your Ubuntu version, python version and the date of binary package . Thanks a lot!

**Comment by Simon-Fuhaoyuan** [comment]
OK, I get the solution. The environment includes ubuntu 16.04 with python 2.7. When downloading drake binary package, please set the date to 20181226. Maybe we can only install from binary package , since building from source cannot satisfy the version of API in this repo. More details when installing drake can be found at https://drake.mit.edu/from_binary.html and https://drake.mit.edu/python_bindings.html#python-bindings-binary

**Comment by caelan** [comment]
Drake is undergoing heavy development, and I haven't updated this example to support the newest version of Drake. You're right in that a user should use an older version of Drake. Thanks for pointing this out.
