### ISSUE TITLE
'examples.pybullet.kuka.run' failed when I used 'AtPose'

### ISSUE THREAD

**Issue by hao-tian-ecnu** [caelan/pddlstream#13]
Hi Caelan,

I really appreciate your great work. I was able to run the example code "examples.pybullet.kuka.run", but when I was trying to revise the goal state, it could not run successfully. I tried 'AtPose', but it didn't work. In order to eliminate the influence of variables, I set the goal object pose as the initial pose. The code in 'pddlstream_from_problem' function is:
```
    #Line 93 function:pddlstream_from_problem
    body = movable[0]
    pose = BodyPose(body, get_pose(body))
    goal = ('and',
            ('AtConf', conf),
            ('AtPose', body, pose),
    )
```
The code with the above goal could not be performed successfully. No matter what pose parameters I tried, all failed. The log shows the Stream plan and Action plan are None:
```
    Attempt: 1 | Results: 24 | Depth: 0 | Success: False
    Stream plan (inf, 0, inf): False
    Action plan (inf, inf): False
```
If I comment the line of 'AtPose', the code can run successfully. I tried to debug it but could not find the reason. Could you help me check this problem? I really appreciate it. 

Thanks,
Nick Tian

**Comment by caelan** [comment]
Hi Nick,

You need to add ```('Pose', body, pose)``` to `init` in order to assert that `pose` is of type pose and is valid for object `body`. See the following line in the original example.

https://github.com/caelan/pddlstream/blob/stable/examples/pybullet/kuka/run.py#L79

Let me know if you have any other issues!

Caelan

**Comment by hao-tian-ecnu** [comment]
Thanks for your response! I just changed your source code "examples.pybullet.kuka.run". I used the following code to replace the original ```goal```.
```
    pose = BodyPose(body, get_pose(body))
    goal = ('and',
            ('AtConf', conf),
            ('AtPose', body, pose),
    )
```
I did not change ```init```, which means ```init``` has added ```('Pose', body, pose)``` at Line 79. But the code could not run successfully.

Thanks,
Nick

**Comment by kzorina** [comment]
The tip suggested in @caelan answer worked for me with:
```
    translate_x = Pose(point=[0.1, 0., 0.])
    desired_pose = multiply(get_pose(body), translate_x)
    desired_body_pose = BodyPose(body, desired_pose)
    init += [('Pose', body, desired_body_pose)]
    goal = ('and',
            ('AtConf', conf),
            ('AtPose', body, desired_body_pose),
    )
```
