### ISSUE TITLE
PyBullet visualization problem

### ISSUE THREAD

**Issue by yijiangh** [caelan/pddlstream#2]
The installation of PDDLStream and pybullet went on well. But when I tried the pr demo: `python -m examples.pybullet.pr2.run`, the visualization didn't work (snapshot below) while the planning itself seems to work smoothly. The only things I can see in the Bullet browser are two moving `cooked` and `cleaned` labels...

I know it is not necessarily PDDLStream's problem and likely to be a pybullet thing, but any hint on this? The pybullet install on my Ubuntu 16.04 is clean without any modification.

![image](https://user-images.githubusercontent.com/11905844/47561492-6481ae00-d8e9-11e8-882c-7c4811268ea7.png)

EDIT: This error has been reproduced on two of my Ubuntu 16.04 visual machines.

**Comment by caelan** [comment]
Hmm, the example runs fine on my Ubuntu 16.04 machine using a version of pybullet installed today. Do all the pybullet examples fail (e.g. python -m examples.pybullet.kuka.run)?

**Comment by yijiangh** [comment]
Find the problem! We need to turn off the 3D graphics acceleration (picture below) on the visual machine to make pybullet's GUI work. After we change that and reboot the vm, we can see our kuka running happily in the `examples.pybullet.kuka` demo.

![image](https://user-images.githubusercontent.com/11905844/47941975-ab157080-dec6-11e8-89fe-8aea49a8c12e.png)
![image](https://user-images.githubusercontent.com/11905844/47941983-bb2d5000-dec6-11e8-96c3-e79147accfe5.png)
