### ISSUE TITLE
How to control the order of the objects to be manipulated?

### ISSUE THREAD

**Issue by hao-tian-ecnu** [caelan/pddlstream#20]
Hi Caelan,

Thanks for your great work. I have tried the example code. I tried to manipulate a set of the same objects without priority to the goal panel. The final result shows the algorithm randomly chooses the object to be manipulated. My question is, if I hope the robot first tries to manipulate a subset of the objects, how could I control the order?

Thanks for your help. Looking forward to your reply. 

Nick

**Comment by caelan** [comment]
Hi Nick,

You can do this by encoding a partial order on objects through the preconditions/effects of PDDL actions. Essentially, you add preconditions that all of a action's preceding actions must be completed before the action in question can be applied.

If you don't need to strictly adhere to an ordering, you can also weakly bias toward this behavior using action costs.

Caelan
