### ISSUE TITLE
incremental algorithm on kitchen example

### ISSUE THREAD

**Issue by MaisJamal** [caelan/pddlstream#26]
Hi Caelan, thanks for sharing your code.
I chose to start with the simplest algorithm, so I'm trying to run the incremental algorithm on the kitchen example. I have commented "stream sample-motion" in stream.pddl and uncommented stream sample-motion-h. Now the incremental algorithm is running to solve the PDDLStream problem but the sample-motion-h stream is always generating the same pose, causing the algorithm to never solve the problem.
Perhaps there are some other things I should edit in the code to get the algorithm running properly. Can you please guide me on how to do that?

**Comment by caelan** [comment]
The kitchen example demonstrates an advanced feature that plans purely optimistically (without real values like trajectories). Try another example like: https://github.com/caelan/pddlstream/blob/main/examples/pybullet/pr2/run.py
