### ISSUE TITLE
Pybullet doesn't have visualization beside for pr2_belief

### ISSUE THREAD

**Issue by roshandhakal** [caelan/pddlstream#27]
Pybullet examples don't have visualization except for pr2_belief. Is it by default and I have to make changes on the code or am I doing something wrong? The following screenshot is the only output I get.
![Screenshot from 2021-10-27 14-25-03](https://user-images.githubusercontent.com/30138013/139124662-d6dd134c-162a-4d94-99a2-7924d7505e4a.png)

**Comment by williamshen-nz** [comment]
If you look at some of the scripts you have to use the `-viewer` flag

```
    parser.add_argument('-viewer', action='store_true', help='Enable the viewer and visualizes the plan')
```

From https://github.com/caelan/pddlstream/blob/main/examples/pybullet/kuka/run.py

**Comment by roshandhakal** [comment]
But, when you see it here; the last argument in the parser, it has that. 
![image](https://user-images.githubusercontent.com/30138013/139717752-93e43772-77c4-4639-b83a-79fdd2481183.png)

**Comment by williamshen-nz** [comment]
That's a `store_true` flag which is set to True only if it is specified, and False otherwise. So you will need to pass the `-viewer` flag so the arg is True.

**Comment by roshandhakal** [comment]
I see. Thank you
