### ISSUE TITLE
What should I specify on domain and stream in order to plan with obstacles on the continuous_tamp example? 

### ISSUE THREAD

**Issue by roshandhakal** [caelan/pddlstream#28]
![image](https://user-images.githubusercontent.com/30138013/142272723-ea6f0b64-5e54-496e-843f-81f63bbc0b36.png)

I want to plan when there is a obstacle like shown in the figure. The obstacle is a black region. I want to plan in a way that robot's trajectory doesn't collide it and as well as the blocks also be clear from the obstacle. 

I tried to specify CFreeTraj on both domain and stream and tried creating function, but that's purely a guess based on how things are done with CFreePose. 

Thank you.

**Comment by caelan** [comment]
This toy domain considers simplified "motion planning" that ignores all collisions except for object-object collisions when placing. Still, this domain is representative of many tabletop manipulation domains when top grasps are available. See the following PyBullet domain for an example that fully enforces collisions (when bug-free): https://github.com/caelan/pddlstream/blob/b01b512b2d2e11dfa407f4bb90319930208fd15a/examples/pybullet/pr2/domain.pddl#L48.
