### ISSUE TITLE
Can't find a plan in the 'Kuka Cleaning and Cooking' scenario using a Panda

### ISSUE THREAD

**Issue by m-morelli** [caelan/pddlstream#30]
Hello, I've tried to change the robot in the 'Kuka Cleaning and Cooking' scenario, using the Franka Panda arm (without hand). Here are the changes I did:
- pybullet_tools/kuka_primitives.py
```
TOOL_FRAMES = {
    'panda': 'panda_link8',
  }
```
- pybullet_tools/utils.py
```
PANDA_ARM_URDF = "models/franka_description/robots/panda_arm.urdf"
```
- models/franka_description/robots/panda_arm.urdf
  - replace every occurrence of `package://franka_description` with `..`
- examples/pybullet/kuka/run.py
```
robot = load_model(PANDA_ARM_URDF, fixed_base=True)
```

However the plan exploration stops after just few attempts and I get the following result:
```
Solved: False
Cost: inf
Length: inf
Deferred: 0
Evaluations: 2
```

The program exits at https://github.com/caelan/pddlstream/blob/main/examples/pybullet/kuka/run.py#L192 (because `plan is None`).

Maybe I need to change something else to use another robot arm? Any (other) hints?
Thanks!
Matteo

**Comment by caelan** [comment]
The planner does not fundamentally depend on the type of robot, and I've planned for Franka Panda robot variants many times before (https://github.com/caelan/SS-Replan/tree/master/models/franka_description/robots). Without more information, I won't be able to debug.
