### ISSUE TITLE
Include individual action costs in solution

### ISSUE THREAD

**Issue by sea-bass** [caelan/pddlstream#36]
When you solve a problem using PDDLStream, you get access to all the individual actions and the total cost of the plan as the first and second elements of the solution tuple.

However, it would be really convenient to also get the cost of each action individually as part of this solution. 

The easiest thing to do would be for the `Action` namedtuple to include `name`, `args`, and an additional `cost` field.

Right now there is the workaround of re-evaluating each cost function for each action in the plan, but it would be nice to avoid having to do this.

**Comment by caelan** [comment]
`get_action_instances` should allow you recover cost info, as well as preconditions and effects, after finding a solution: https://github.com/caelan/pddlstream/blob/2c7d6f514b07ed018e18710192aa0f91c2e70ee2/pddlstream/algorithms/downward.py#L597

**Comment by scastro-bdai** [comment]
I was looking into this after... some time, and am running into a wall.

I added this to my invocation of `solve_abstract`:

```python
    from pddlstream.algorithms.downward import task_from_domain_problem, get_action_instances, get_problem, parse_sequential_domain

    domain = parse_sequential_domain(problem.domain_pddl)
    problem = get_problem(evaluations, goal_exp, domain, unit_costs)
    task = task_from_domain_problem(domain, problem)
    solution = store.extract_solution()
    instances = get_action_instances(task, store.best_plan.action_plan)
```

In calling `get_action_instances`, I hit this part of the code: 
https://github.com/caelan/pddlstream/blob/2c7d6f514b07ed018e18710192aa0f91c2e70ee2/pddlstream/algorithms/downward.py#L613

which implies that something can't instantiate even though the plan is totally valid?

I'm 95% sure I am passing the wrong variables names into all these functions, though. Any ideas?

**Comment by sea-bass** [comment]
I was looking into this after... some time, and am running into a wall.

I tried adding this to my invocation of `solve_abstract()` at the end:

```python
    from pddlstream.algorithms.downward import task_from_domain_problem, get_action_instances, get_problem, parse_sequential_domain

    domain = parse_sequential_domain(problem.domain_pddl)
    problem = get_problem(evaluations, goal_exp, domain, unit_costs)
    task = task_from_domain_problem(domain, problem)
    solution = store.extract_solution()
    instances = get_action_instances(task, store.best_plan.action_plan)
```

In calling `get_action_instances`, I hit this part of the code: 
https://github.com/caelan/pddlstream/blob/2c7d6f514b07ed018e18710192aa0f91c2e70ee2/pddlstream/algorithms/downward.py#L613

which implies that something can't instantiate even though the plan is totally valid?

I'm 95% sure I am passing the wrong variables names into all these functions, though. Any ideas?
