### ISSUE TITLE
Easiest way to extract predicate value

### ISSUE THREAD

**Issue by danfeiX** [caelan/pddlstream#5]
What would be the easiest way to tell if a predicate is true given the current state of the environment? Looks like the evaluations returned by `solve_focused` are for the entire plan.

**Comment by caelan** [comment]
By current state of the environment, do you mean planning state, as in, a state resulting from applying several action instances to init? I currently don't have this functionality exposed in a user-friendly way. However, you can use following method to apply an action instance to a set of atoms.

https://github.com/caelan/pddlstream/blob/stable/pddlstream/algorithms/downward.py#L321

The evaluations returned by each algorithm are actually facts proven about the initial state. Many of these facts are static though; they are true in all states.

**Comment by danfeiX** [comment]
Thanks for the response! I actually meant the state of the simulation world (body pose, gripper state, etc). This is already useful to know, but would it be possible to evaluate the predicate at each simulation step?

**Comment by caelan** [comment]
Some of the fluent predicates (AtConf, AtPose, ...) are functionally defined using just the current pybullet state. Others, such as AtGrasp, currently require additional state knowledge regarding whether the robot has rigidly attached itself to a movable body. Computing AtGrasp directly from the pybullet state would require determining whether the end effector is exerting a grasping force on a movable body. 

Here's an example planning and acting under uncertainty task where I evaluate the fluent state several times during execution: 
https://github.com/caelan/pddlstream/blob/stable/examples/pybullet/pr2_belief/run.py#L34
