### ISSUE TITLE
file handle leak

### ISSUE THREAD

**Issue by danfeiX** [caelan/pddlstream#9]
I noticed that there are some file handle leaks in the code. The symptom is that if you run the planning, e.g., solve_focused in an infinite loop, eventually it will crash with `OSError: [Errno 24] Too many open files: 'temp/'`. I've been looking for where the leak happens, but no luck so far. You did a really great job in blocking such leak by using context manager for opening files. Hence I suspect the leak happens in the FastDownward process as opposed to the main python process, but it's just a guess.

**Comment by danfeiX** [comment]
Ok here is more info: It looks like the leaked fds are STDIN/STDOUT's. The proc/pid/fd folder has hundreds of fds pointing to /dev/pts/*.

**Comment by danfeiX** [comment]
Ok I've found the bug. There is a file handle leak under HideOutput. https://github.com/caelan/ss-pybullet/blob/320e39b461f862a82b68a10aae096efed42d87dd/pybullet_tools/utils.py#L134 You should also close `self._oldstdout_fno` at the end, i.e., os.close(self._oldstdout_fno)

**Comment by caelan** [comment]
Thanks for catching this. I'm pushing the fix.
